### ISSUE TITLE
Waveguide instruments are not in tune

### ISSUE THREAD

**Issue by pizzafilms** [thestk/stk#100]
I can see that the waveguide instruments (mandolin, etc) use an allpass delay line as well as a one pole filter for the loss filter. When the frequency is set for an instrument, it sets the delay line length and subtracts the phase delay of the loss filter to compensate and correct the pitch. But...it's not in tune. A-440 plays at 436 Hz, A-880 plays around 862 Hz, and A-1760 plays around  1694 Hz.

Is there a problem with the algorithm itself? Or the way phase delay is calculated?

**Comment by garyscavone** [comment]
The delay compensation in the instruments was not rigorously tested. There may be an extra sample of delay that was missed, just because of the way the functions are called (for example, using lastOut()). What happens if you subtract another sample from the delay length?

**Comment by ananthp** [comment]
Did anyone try the proposed workaround?

Currently waveguide instruments play frequency lower than what's asked for, and the difference between the excepted and actual frequencies grows as we go up the spectrum. At around 1500 Hz, the difference is about -50 cents, meaning the pitch is very flat.

```
Hz expected | actual   |  cents difference
---------------------------------------------
plucked
     100.0      99.79      -3.64
     200.0     199.22      -6.77
     300.0     298.00     -11.58
     400.0     396.70     -14.34
     500.0     495.00     -17.40
     600.0     592.70     -21.19
     700.0     690.20     -24.41
     800.0     786.94     -28.50
     900.0     883.36     -32.31
    1000.0     979.40     -36.04
    1100.0    1075.70     -38.67
    1200.0    1170.60     -42.94
    1300.0    1266.50     -45.20
    1400.0    1359.80     -50.44
    1500.0    1455.00     -52.73

mandolin
     100.0      99.80      -3.47
     200.0     199.16      -7.29
     300.0     298.13     -10.83
     400.0     396.70     -14.34
     500.0     495.00     -17.40
     600.0     592.60     -21.48
     700.0     690.00     -24.91
     800.0     786.90     -28.58
     900.0     883.50     -32.03
    1000.0     979.80     -35.33
    1100.0    1075.60     -38.83
    1200.0    1171.00     -42.35
    1300.0    1262.00     -51.36
    1400.0    1360.00     -50.18
    1500.0    1457.50     -49.76

saxofony
     100.0      99.80      -3.47
     200.0     199.00      -8.68
     300.0     297.50     -14.49
     400.0     395.50     -19.59
     500.0     493.15     -23.88
     600.0     591.50     -24.70
     700.0     687.50     -31.19
     800.0     783.30     -36.52
     900.0     879.50     -39.89
    1000.0     974.80     -44.19
    1100.0    1069.40     -48.84
    1200.0    1164.00     -52.73
    1300.0    1258.00     -56.86
    1400.0    1351.00     -61.68
    1500.0    1445.00     -64.67
```

`Bowed` sometimes start at a desired pitch range, but jumps up an octave.

```
bowed
     100.0     200.06    1200.52
     200.0     400.24    1201.04
     300.0     300.60       3.46
     400.0     401.00       4.32
     500.0     501.90       6.57
     600.0    1200.00    1200.00
     700.0    1407.00    1208.63
     800.0    1611.00    1211.86
     900.0    1815.00    1214.37
    1000.0    2020.00    1217.23
    1100.0    2225.00    1219.56
    1200.0    2528.00    1289.95
    1300.0    2635.00    1223.15
    1400.0    2840.00    1224.56
    1500.0    3048.00    1227.48
```

Is there anything that the library users can do to work around this problem?

**Comment by garyscavone** [comment]
There may be an inherent extra delay or more in the way the algorithms are implemented (using old state for a current computation). One would have to carefully go through the code and analyze the situation. Honestly, it’s not something I have time to do and I don’t consider it a priority issue. But if you figure out how to fix it, please submit a PR.
