### ISSUE TITLE
error: use of undeclared identifier 'getpid' and 'usleep'

### ISSUE THREAD

**Issue by ryandesign** [thestk/stk#102]
[stk 4.6.1 failed to build](https://build.macports.org/builders/ports-10.6_i386-builder/builds/14452/steps/install-port/logs/stdio) on Mac OS X 10.6 using open source clang 9.0.1 (so I don't know if the issue is caused by the old OS or the new compiler):

```
RtAudio.cpp:1128:21: error: use of undeclared identifier 'getpid'
    if ( hog_pid != getpid() ) {
                    ^
RtAudio.cpp:1129:17: error: use of undeclared identifier 'getpid'
      hog_pid = getpid();
                ^
RtAudio.cpp:1177:7: error: use of undeclared identifier 'usleep'
      usleep( 5000 );
      ^
3 errors generated.
```

The solution is to:

```
#include <unistd.h>
```

RtAudio.cpp is over 10,000 lines long so I'm not going to attempt to understand it. I see that it already includes unistd.h conditionally in 4 places, but apparently you're using getpid and usleep outside of those places and need to include unistd.h there too.

**Comment by garyscavone** [comment]
This is an RtAudio issue, which is supported in its own github repo. I made the update there without fixing it here, as hopefully we'll put out a new release in the near future.
