### ISSUE TITLE
RtWvOut destructor - infinite loop

### ISSUE THREAD

**Issue by vuki** [thestk/stk#104]
`RtWvOut` class object goes into an infinite loop if the destructor is called while the stream is not running (it was stopped or never started).
Minimal example:
```
#include "RtWvOut.h"
RtWvOut* dac = new RtWvOut(1);
delete dac;
```

This is the `RtWvOut` destructor:
```
RtWvOut :: ~RtWvOut( void )
{
  // Change status flag to signal callback to clear the buffer and close.
  status_ = EMPTYING;
  while ( status_ != FINISHED || dac_.isStreamRunning() == true ) Stk::sleep( 100 );
  dac_.closeStream();
}
```

The stream is not runnning, so `dac_.isStreamRunning()` is always `false`. At the same time, since the stream is not running, `readBuffer` will never be called and `status_` will forever be stuck at `EMPTYING`, resulting in an infinite loop.

Shouldn't  `||` be `&&` instead?
```
  while ( status_ != FINISHED && dac_.isStreamRunning() ) Stk::sleep( 100 );
```

**Comment by garyscavone** [comment]
Yes, that looks like a bug ... surprised it hasn't come up before. Can you submit a PR?

**Comment by vuki** [comment]
Done, #105
