### ISSUE TITLE
Blowups and clipping in the stk::Sitar class

### ISSUE THREAD

**Issue by gogins** [thestk/stk#117]
See the Csound plugins issue https://github.com/csound/plugins/issues/4 for more information.

The following patch fixes the Csound issue:
mkg@xenakis:~/stk$ git diff
diff --git a/src/Sitar.cpp b/src/Sitar.cpp
index 2d3364e..11c493e 100644
--- a/src/Sitar.cpp
+++ b/src/Sitar.cpp
@@ -61,7 +61,7 @@ void Sitar :: setFrequency( StkFloat frequency )
 #endif
 
   targetDelay_ = (Stk::sampleRate() / frequency);
-  delay_ = targetDelay_ * (1.0 + (0.05 * noise_.tick()));
+  delay_ = targetDelay_;
   delayLine_.setDelay( delay_ );
   loopGain_ = 0.995 + (frequency * 0.0000005);
   if ( loopGain_ > 0.9995 ) loopGain_ = 0.9995;
mkg@xenakis:~/stk$ 
```

**Comment by umlaeute** [comment]
thanks for debugging this.
afaics, the incriminating line just adds a little jitter to the delay, e.g. to either prevent phase cancelling or/and make the sounds more lively.
in https://github.com/csound/plugins/issues/4#issuecomment-932993431 (gone by now) you indicated that the delay was actually set to `0`, which i wouldn't have expected (unless `noise_.tick()` emits `-20`).
probably a better solution would be:
```C
delay_ = targetDelay_ * (1.0 + (0.05 * fabs(noise_.tick())));
```

**Comment by gogins** [comment]
The STK developers have not even assigned the issue I created in their repository, but this is no longer a Csound issue.
