### ISSUE TITLE
Modalbar missing setModulationDepth

### ISSUE THREAD

**Issue by TomCoalfish** [thestk/stk#124]
The function is not defined.

I think it is supposed to be vibrato_.setFrequency( normalizedValue * 12.0 );

GCC has a flag that can tell you what functions are declared without a body.

**Comment by TomCoalfish** [comment]
Twang is missing setLoopFilter

I don't think these are extremely important, they are never used anywhere in the library. Only if you try to call it, it will probably crash as it is never define. I do not know what Twang::setLoopFilter is supposed to do so I ignore it.

**Comment by garyscavone** [comment]
Thanks ... I just added these.
