### ISSUE TITLE
Dynamic library not installed properly

### ISSUE THREAD

**Issue by rdpoor** [thestk/stk#28]
Makefile is slightly dyslexic, with the following results:

```
$ cd src
$ ./configure -prefix=/Users/r/Projects/Mu/usr
...
$ make install
...
cp -r ../include/*.h /Users/r/Projects/Mu/usr/include/stk
install -d /Users/r/Projects/Mu/usr/lib
install -m 644 libstk.dylib.4.4.4 /Users/r/Projects/Mu/usr/lib
install: libstk.dylib.4.4.4: No such file or directory
make[2]: *** [install] Error 71
make[1]: *** [install] Error 2
make: *** [/Users/r/Projects/Mu/usr/lib/libstk.a] Error 2
```

It appears that Makefile disagrees with itself.  Around line 90, it's creating 'libstk.4.4.4.dylib':

```
# Makefile line 90
$(SHAREDLIB) : $(OBJECTS)
    $(RM) -f $(@) $(SHAREDLIB).$(MAJOR) $(SHAREDLIB)
    $(CC) $(LDFLAGS) -fPIC -dynamiclib -o libstk.$(RELEASE).dylib $(OBJECT_PATH)/*.o $(LIBS)
    $(LN) -s libstk.$(RELEASE).dylib $(SHAREDLIB)
    # $(LN) -s libstk.$(RELEASE).dylib $(SHAREDLIB).$(MAJOR)
```

... but around line 100, it's trying to install 'libstk.dylib.4.4.4':

```
install: $(SHAREDLIB) install-headers
    install -d $(DESTDIR)$(PREFIX)$(LIBDIR)
    install -m 644 $(SHAREDLIB).$(RELEASE) $(DESTDIR)$(PREFIX)$(LIBDIR)
    ln -sf $(SHAREDLIB).$(RELEASE) $(DESTDIR)$(PREFIX)$(LIBDIR)/$(SHAREDLIB)
    ln -sf $(SHAREDLIB).$(RELEASE) $(DESTDIR)$(PREFIX)$(LIBDIR)/$(SHAREDLIB).$(MAJOR)
```

According to https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html#//apple_ref/doc/uid/TP40002013-SW19, it appears that the correct name would be `libstk.4.dylib`, where `4` is the major version number.  

I'd change it, but I have no idea how many other apps depend on the name of the shared library.

**Comment by rdpoor** [comment]
Okay - I've been rebuilding my system and think I understand Makefile.in a little better.  I think I have an actual (??) fix.  In lieu of a pull request, here are the changes.  (Aside: do you want a pull request?)

In `src/Makefile.in`, change lines 102-104 from:

        install -m 644 $(SHAREDLIB).$(RELEASE) $(DESTDIR)$(PREFIX)$(LIBDIR)
        ln -sf $(SHAREDLIB).$(RELEASE) $(DESTDIR)$(PREFIX)$(LIBDIR)/$(SHAREDLIB)
        ln -sf $(SHAREDLIB).$(RELEASE) $(DESTDIR)$(PREFIX)$(LIBDIR)/$(SHAREDLIB).$(MAJOR)

to

        install -m 644 @sharedname@ $(DESTDIR)$(PREFIX)$(LIBDIR)
	ln -sf @sharedname@ $(DESTDIR)$(PREFIX)$(LIBDIR)/$(SHAREDLIB)
        ln -sf @sharedname@ $(DESTDIR)$(PREFIX)$(LIBDIR)/$(SHAREDLIB).$(MAJOR)

As best I can predict, this should work on both Windows and OS X.  But I've confirmed it works on the latter.  (There's still a separate problem concerning absolute pathnames for the shared lib, but I'll treat that in a separate issue.)

**Comment by rdpoor** [comment]
update: I've forked the most recent repo and I'm working on creating a pull request.  standby...

**Comment by arielelkin** [comment]
@rdpoor any updates on this issue? would you like to send in a pull request?

**Comment by radarsat1** [comment]
I guess the proposed change is here:  https://github.com/rdpoor/stk/commit/6094f36013388b2f8f838d59acc4bab18020be39

Can an OS X use verify that this is a good change to make? If so I'll pull it and close this old issue.

**Comment by radarsat1** [comment]
Can anyone test this?

**Comment by radarsat1** [comment]
I just tried this and it doesn't seem to make a difference.  Checked with otool -L etc and couldn't see a difference in the library linkage.  It seems some things regarding the naming of the dylib have changed since this work anyways.  If the original author @rdpoor can still provide a recommendation, please feel free to re-open.

I'll close for now, I think this is best left to a larger overhaul of the build system (e.g. move to libtool/automake or cmake)
