### ISSUE TITLE
compiling with _STK_DEBUG__

### ISSUE THREAD

**Issue by sonoro1234** [thestk/stk#41]
error on Stk.cpp:361
 f not defined
on 363
not terminated string

**Comment by rdpoor** [comment]
Looks like that came in with this:

https://github.com/thestk/stk/commit/46be0d56c3968207b16900304b0dff519042976a

This fix looks obvious -- perhaps https://github.com/Ahbee should get first crack at it?

**Comment by sonoro1234** [comment]
please apply fix to master
