### ISSUE TITLE
noise reading files?

### ISSUE THREAD

**Issue by sonoro1234** [thestk/stk#43]
I am doing a new stk wrapping for supercollider.
Some instruments are noisy, I think that all of them do read files.
then I did:
demo Simple -or -if scores/duelingb.ski
and the noise appears also.
Is this expected?
Best
victor bombi

**Comment by garyscavone** [comment]
Did you specify a particular endianness as a preprocessor definition when compiling?  For example, when compiling with an intel processor, you need __LITTLE_ENDIAN__ as a preprocessor definition (and the appropriate flag, which is -D for g++).

�gary

**Comment by sonoro1234** [comment]
my fault: 
first Simple is not so simple, it has noise in the generator.
second : I should have readen compiling instructions
__LITTLE_ENDIAN__ was the key
Thanyou very much
victor
