### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by fsateler** [thestk/stk#45]
Several fixes have accumulated, it would be good to have a new release.

**Comment by fsateler** [comment]
ping

**Comment by rvega** [comment]
+1 :)

**Comment by hzulla** [comment]
Yay for a new release!

**Comment by arielelkin** [comment]
FYI this is currently being discussed in the mailing list: 
https://cm-mail.stanford.edu/pipermail/stk/2016-August/thread.html

**Comment by garyscavone** [comment]
This should have been closed after the last release.
