### ISSUE TITLE
std::vector alertList_

### ISSUE THREAD

**Issue by sonoro1234** [thestk/stk#50]
Hi,

While doing a new binding of Stk for supercollider (StkInst) and after having overloaded new and delete for using supercollider real-time memory (RTAlloc and RTFree) I had crashes when quiting scserver.
My search concludes that alertList_ was responsible of that: being a global it is freed so late that RTFree is not operative. It does not matter if the vector is empty because it always reserves some memory (vector capacity). The only way to really free all memory reserved by the vector is:
```
std::vector<Stk *>().swap(Stk::alertList_);
```
but it must be done from inside Stk class because alertList_ is private, so my solution was adding a method 
```
void Stk :: clear_alertList(){std::vector<Stk *>().swap(alertList_);}
```
that I can call on exit to force memory being freed and this solved my problem.

I would prefer not having to patch Stk but have this method in regular Stk distribution.

Shall I make a pull request for that?

Best
victor bombi

**Comment by sonoro1234** [comment]
@garyscavone please tell me what do you think about it.

**Comment by garyscavone** [comment]
Hi Victor,

It seems like a bit of a hack but the solution is fairly minimal and seemingly harmless, so that is fine with me.  You can make it a pull request.

Regards,

—gary

**Comment by arielelkin** [comment]
resolved by https://github.com/thestk/stk/pull/51
