### ISSUE TITLE
How to make dll or obj file for windows

### ISSUE THREAD

**Issue by cheyuanl** [thestk/stk#59]
I use minGW but it make the so file. Is it possible to make the dll, obj for windows?

**Comment by kevin1** [comment]
It might be easiest to compile the library with Visual Studio. They recently added a clang frontend, so now it has source compatibility with clang and therefore gcc.

**Comment by paulsapps** [comment]
This code builds ok with msvc anyways

**Comment by cheyuanl** [comment]
Could you elaborate? I am not familiar with windows and how to build library with msvc. Thanks a lot!

**Comment by radarsat1** [comment]
Isn't it possible to get a DLL from MingW?

**Comment by cheyuanl** [comment]
Thanks a lot , I just build with source anyway.
