### ISSUE TITLE
skini.cpp::parseString ignores arguments for midi extension statements

### ISSUE THREAD

**Issue by rhenninger** [thestk/stk#63]
parseString relies on dual usage for the iValue variable: as index for skini::Message arguments and as index for the parsed token array.  This works for all cases except midi extension messages where decrementing iValue in default: causes the parser to bail out before parsing its DBL argument.  One solution might be to have two separate indexes 1) an increment to the token index during DBL and INT but not in default: case while still 2) incrementing the index into skini::Message's arguments.

**Comment by garyscavone** [comment]
If you have a fix, please submit it as a pull request.  That would be the most expedient way to get this fixed, since it would take me a while to become familiar with the problem and find a particular example where I can recreate it.  Otherwise, it would help if you could specify line numbers where the problem occurs.

**Comment by rhenninger** [comment]
I have a working and tested fix in my personal copy of the stk.   However, my copy is highly modified in other areas as I try to fit the stk into a form usable in the MS Hololens using Unity.  I can make a separate clean clone and make the changes there and make a pull request out of that, I suppose.  Looking at the site, it appears that I would do this off of the master branch (in that I don’t see any other active branches), right?

                The fix I did is in the final loop of parseString in Skini.cpp (ca lines 157-191) using separate variables to index the tokens and the output arguments.  In the failing case, simply adding 3 to the existing index causes to loop to exit without parsing the final argument. Each index increments differently depending on data type.
