### ISSUE TITLE
Reopen RtAudio stream

### ISSUE THREAD

**Issue by jercaianu** [thestk/stk#67]
Hello, I am having issues with reopening a stream. 
What I would like to do is load a wav file, call openStream to play and process it in my tick function. Later, I may want to load a different wav file and play it.
I am trying to achieve this by calling closeStream and again openStream with the input buffer set to the new file, but this approach does not seem to work.
Can someone please help me solve this issue?

Thanks,
Alex

**Comment by radarsat1** [comment]
No need to close the stream probably but closing and re-opening shouldn't be a big deal normally.  Can you post some example code?  System info?

**Comment by garyscavone** [comment]
There is a “teststops.cpp” program file in the “tests/“ subdirectory that was specifically designed to test this.  It worked when I last tried it.
