### ISSUE TITLE
Build wavetables (rawwaves) into source code

### ISSUE THREAD

**Issue by gogins** [thestk/stk#70]
I am the author and maintainer of Csound opcodes that wrap the STK instrument classes (https://github.com/csound/csound/blob/develop/Opcodes/stk/stkOpcodes.cpp). It would greatly facilitate encapsulating the STK in Csound and in other projects if there were an option to bring all of the rawwaves wavetables into RAM and into the actual source code such that there would be no need to read this data from storage and no need to locate this storage at run time.

**Comment by radarsat1** [comment]
I completely agree.  I like the idea of making it a build option actually.  The waves are a fundamental part of the oscillators, no reason to consider them special.

**Comment by garyscavone** [comment]
I would be in favour of this, assuming it does not add complexity to the configuration and build process. Does someone have a suggestion on how to do it?

**Comment by gogins** [comment]
It is definitely possible to directly #include the rawwaves data as static
arrays in the C++ source code.

You can use the xxd utility to create snippets of code to #include, e.g. I
just tried this:

mkg@Sun-Yukong:~/csound/csound/android/pluginlibs/stk/rawwaves$ xxd -i
eee.raw
unsigned char eee_raw[] = {
  0xfe, 0x31, 0x02, 0xea, 0x01, 0x29, 0x07, 0x08, 0x10, 0x40, 0x0f, 0x26,
  0x0e, 0x3d, 0x14, 0x51, 0x12, 0xc1, 0x11, 0x23, 0x17, 0x3d, 0x16, 0x1d,
  0x11, 0x95, 0x11, 0x4d, 0x0f, 0xbd, 0x0d, 0xa6, 0x0d, 0x3e, 0x09, 0xc3,
  0x05, 0x25, 0x03, 0xca, 0xff, 0x70, 0xfa, 0xc9, 0xfa, 0x33, 0xf7, 0xa2,
  0xf4, 0xf9, 0xf4, 0x4e, 0xf1, 0xc3, 0xee, 0x82, 0xee, 0x24, 0xee, 0xce,
  0xed, 0x43, 0xea, 0x5d, 0xe9, 0x17, 0xec, 0x4b, 0xeb, 0xc3, 0xe6, 0x21,
  0xeb, 0x21, 0xf4, 0x7f, 0xee, 0xc3, 0xea, 0x0e, 0xf7, 0xf6, 0xfd, 0x8b,
  0xf4, 0x03, 0xfb, 0xbe, 0x0b, 0x41, 0x03, 0xd8, 0xfe, 0xbf, 0x11, 0x46,
  0x17, 0x00, 0x0a, 0xaa, 0x10, 0x7d, 0x1d, 0x4c, 0x15, 0xd1, 0x11, 0x63,
  0x1c, 0xdd, 0x1d, 0x1d, 0x14, 0x50, 0x15, 0xcd, 0x18, 0x5d, 0x13, 0x86,
  0x10, 0x9e, 0x0e, 0xb6, 0x0a, 0xad, 0x08, 0xca, 0x03, 0x69, 0xfc, 0xf8,
  0xfc, 0xeb, 0xf8, 0x32, 0xea, 0xd6, 0xe6, 0x6d, 0xeb, 0x03, 0xe5, 0x72,
  0xdc, 0xb4, 0xe1, 0x1a, 0xe1, 0xa3, 0xd5, 0x16, 0xd5, 0x76, 0xe2, 0x36,
  0xde, 0xa3, 0xd4, 0xd7, 0xdc, 0xda, 0xe3, 0x7e, 0xde, 0xa3, 0xe3, 0xe7,
  0xec, 0xb1, 0xeb, 0x73, 0xeb, 0xc3, 0xf3, 0xd5, 0xfb, 0x2f, 0xfd, 0x83,
  0xfe, 0x77, 0xfe, 0x31
};
unsigned int eee_raw_len = 184;

Then you would type cast eee_raw to float[] and divide the length by 4:

float *eee_float= static_cast<float *>(&eee_raw[0]);
eee_float_len = eee_raw_len / 4;

There may be more elegant ways of doing this, but this would surely work.

Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by radarsat1** [comment]
There are more elegant ways using objcopy and ld, but then I would imagine it might lead to compatibility issues on different platforms. So, probably @gogins suggestion is better, if ugly.  Anyways, I'll take a shot at it when I get a chance, but in the meantime, PRs will be considered ;)

**Comment by radarsat1** [comment]
Apart from how to embed the data, there is the problem of how to integrate it. I looked briefly at how raw waves are used and it seems they are used mainly in two contexts: as sound files (FileWvIn) and as loops (wave tables, aka FileLoop).

Currently FileLoop inherits from FileWvIn.  I think what I'd do to abstract a bit the provenance of the wave data, is to change FileLoop for WvLoop, which takes a WvIn as argument, so that it's no longer bound to FileWvIn.  Then add a sister class to FileWvIn called MemoryWvIn that provides the data from in-memory arrays.  Well, just an idea, I'll see how easy that is to actually do.

**Comment by paulsapps** [comment]
This might prove handy: https://github.com/ocornut/imgui/blob/master/extra_fonts/binary_to_compressed_c.cpp

**Comment by radarsat1** [comment]
Alright I took a shot at it but that approach started to get a bit overcomplicated.  Maybe simpler to just override FileWvIn and FileLoop and put some #ifdefs around where they are instantiated.
