### ISSUE TITLE
Jack support should not require ALSA

### ISSUE THREAD

**Issue by yurivict** [thestk/stk#72]
> AC_CHECK_LIB(asound, snd_pcm_open, , AC_MSG_ERROR(Jack support also requires the asound library!))], )

Jack is independent of ALSA in both sound and MIDI.

**Comment by garyscavone** [comment]
Can someone with a linux box confirm this? I thought that in the past, Jack was built on top of ALSA.

**Comment by yurivict** [comment]
No, Jack works over OSS as well.
Jack is a separate API/protocol, independent of ALSA.

**Comment by radarsat1** [comment]
I don't think anyone will use it with OSS but it's valid that it might be interesting to make it work with Jack on OS X.  I don't know if anything special is required for that.  @yurivict is it just a question of tweaking the configure script or are there build-time dependencies that should be removed? (e.g. headers that shouldn't be included..)

**Comment by yurivict** [comment]
> I don't think anyone will use it with OSS

What do you mean?

FreeBSD uses OSS, and Jack is used with OSS there. There is an stk port on the FreeBSD.

**Comment by radarsat1** [comment]
Fair enough.  OSS is basically obsolete on Linux, and I don't know anyone who uses FreeBSD, so ymmv.  As one of very few OSS users, it would be great if you could test OSS support!  Can you make any new issues if regarding whether it builds/tests correctly?

As for JACK, did you try taking out that line in configure.ac?

**Comment by yurivict** [comment]
It actually builds on OSS-only system fine once ```AC_CHECK_LIB(asound ...)``` is removed. So you need to create a configure flag, ex. --disable-alsa and only perform the above ```AC_CHECK_LIB``` in case it's not disabled.

**Comment by yurivict** [comment]
Good news is that this is the only problem.
Thanks for your help!
