### ISSUE TITLE
TwoZero::sampleRateChanged: you may need to recompute filter coefficients!

### ISSUE THREAD

**Issue by yurivict** [thestk/stk#77]
Using ```BeeThree.h``` causes this warning.
I think, this call ```Stk::setSampleRate(sampleRate);``` triggers the warning.
The warning should suggest what should be called to recompute coefficients, or stk should do it by itself.

**Comment by garyscavone** [comment]
This should only happen if the sample rate was changed after the instrument was created. This does not appear to be a bug but rather a usage issue.
