### ISSUE TITLE
Windows refresh + ASIO

### ISSUE THREAD

**Issue by cepthomas** [thestk/stk#87]
Hi. As part of my other audio experiments I wanted to incorporate some wave/sound generating capability. I decided stk was the best option based on several criteria. As the current VS build configs are stale, I updated them to support VS2017. I also spent some time debugging the ASIO support but didn't quite get through that completely.

So, I would like to formalize these steps and give back my learnings. My thought is to branch and create a new project folder with an updated win stk build + ASIO + OSC server (because this is what I really want for my experiments). I can do this with VS but also strongly consider using Qt/mingw/QMake/QtCreator which I consider a superior environment for C++ applications (even vanilla ones that don't use Qt libs). 

If this is acceptable and successfully implemented, then consideration can be given to updating the other projects.

**Comment by ntonnaett** [comment]
Maybe looking into meson would be worth it. It has VS (even 2017) and XCode backends. Project description would be only in one place.

**Comment by radarsat1** [comment]
I think it's better to not implement yet another build system for this software :joy: there's been sufficient work on that in RtAudio / RtMidi so if anything perhaps a CMake system to complement as with those projects, but I can't guarantee it will be accepted for inclusion.  Probably it's ok to just update the VS project files, although considering they are still loadable I don't know if it even makes sense to change them as they "support" all versions of VS.  However what @cepthomas is proposing is any sufficiently divergent from how STK works that it's probably better to develop it as a fork and then we can see what is useful to merge.  I agree that a Qt interface could be cool, but would likely only be accepted here if it can be put "along side" the Wish interface, not replacing it.  Same with a CMake project, feel free to develop it separately for now but just know that it's not considered critical to this project to integrate new UIs, build systems, etc.

**Comment by cepthomas** [comment]
I'm not proposing a new universal build system - I see that there's been plenty of discussion about CMake etc, and the current system works fine for a mature application, except for VS support. If you load the e.g. current demo project dsw/dsp files into VS2017, the one way update will fail. It's a minor fix and the new sln/vcxproj files could cohabit comfortably. That would then enable me to dive into the real problem - getting asio working properly.

As far as Qt goes, I was not implying using the UI aspects as a replacement for the tcl stuff. Several times in the past I have been gifted with some nasty old crusty C/C++ projects and some presumably functional version of Eclipse CDT. Never once have I gotten that toolset to work correctly, much hair-pulling and cursing. I found that it was incredibly simple to wrap an existing codebase in a QMake project structure, fire up the QtCreator IDE and get to work immediately. And guess what? It supports cross platform dev! Well, at least the win/linux is easy - I know nothing of osx dev.

So maybe the approach should be to branch the demo project (or other if you think), get it building under VS2017, merge that, then start on the asio stuff?

**Comment by cepthomas** [comment]
Oops...

**Comment by garyscavone** [comment]
Before you do that, I would grab the RtAudio project and see if ASIO builds there. I think the ASIO files in the STK project are outdated but have been updated in RtAudio. This is normal, as we don’t copy over updates from RtAudio until we’re ready to make a new release of STK.

I have used the QMake system and I like it but I don’t want to require users to have to download it to use STK.

**Comment by cepthomas** [comment]
> Before you do that, I would grab the RtAudio project and see if ASIO builds there. I think the ASIO files in the STK project are outdated but have been updated in RtAudio. This is normal, as we don’t copy over updates from RtAudio until we’re ready to make a new release of STK.

Thanks for the heads up. It builds OK, just won't run happily, at least with asio4all.

> I have used the QMake system and I like it but I don’t want to require users to have to download it to use STK.

Understood. I'm a simpler-better type myself, just throwing it out there as a nice alternative.

**Comment by radarsat1** [comment]
Ok, with build system questions out of the way, can you explain what is actually a problem with ASIO?
Perhaps you could open an issue on RtAudio about it, what do you mean exactly by "won't run happily"?  Do you get over/underruns?

**Comment by Karbonforms** [comment]
When I needed ASIO for a test synth project, I just used JUCE and pulled in the STK files I needed. Was insanely easy and effective. Don't think I've ever 'built' the STK despite messing about with it for years now.

**Comment by cepthomas** [comment]
> Ok, with build system questions out of the way, can you explain what is actually a problem with ASIO?
> Perhaps you could open an issue on RtAudio about it, what do you mean exactly by "won't run happily"? Do you get over/underruns?

Honestly I don't remember the details, just that I left a note for myself:
`dac.startStream(); // TODO asio gets mad starting here`
Definitely a rigorous QA department. :unamused:

Anyways, since I was not aware that the stk audio files are a bit stale, I will try to recreate my issue with the fresh files and report back to RtAudio if there are still issues (guessing there won't be).

**Comment by cepthomas** [comment]
> When I needed ASIO for a test synth project, I just used JUCE and pulled in the STK files I needed. Was insanely easy and effective. Don't think I've ever 'built' the STK despite messing about with it for years now.

I dabbled with Juce a while back and thought it was a really nicely architected large C++ application, no easy task. It would be the way to go for a commercial product I think but was more than I wanted to bite off since all I really want to do is manipulate stk from a windows client. My original intent was to build it as a C++/CLI app but I figured the GC would eventually bite me badly. So - build a standalone stk server running asio and conversing using OSC. And hand over any useful parts to the community.

**Comment by Karbonforms** [comment]
OK man. Just saying, juce does OSC (and MPE, and VST, and MIDI..., builds for Win/Mac/Linux/iOS/Android. It's an audio tinkerers dream (to me anyway!))

**Comment by cepthomas** [comment]
Agreed, JUCE is quite a clever package. I was playing with it as a VSTi
host for third party synths, rather than pretending I could write one
better. Now you have my interest re-piqued, maybe I'll have to load it up
again.

Chris

**Comment by radarsat1** [comment]
So, just to be clear, I think any work towards making a new UI for STK using JUCE, Qt, or whatever, is wholeheartedly encouraged!  Only to say that probably such an effort would need to be made a separate project (ie fork), since it would represent quite a huge change in the code organisation.  In that sense, if anyone is willing to start such a project and maintain it, please link it here, because I for one am interested in knowing about it and taking a look and even helping.  Just don't expect large and wild PRs to be merged here, per se, but that definitely shouldn't stop you from working on it if you are motivated.

One a project is started or decided not to be started, please link it here and close the issue.  (In the sense that it's not a bug report..)  New issues in the new project should be opened to discuss specifics of the redesign.

With regards to ASIO, please do report if it is fixed by updating RtAudio.

**Comment by cepthomas** [comment]
> With regards to ASIO, please do report if it is fixed by updating RtAudio.

Whatever I was doing (wrong) before, everything seems ok now ASIO-wise. I built and ran successfully using both the "old" and "new" RtAudio source and the demo project using VS2017. This consisted of just realtime operation with skini file playing, and midi input. So, if useful, I can provide those sln/proj files in the current demo project and close this issue. Note that no source has been changed. The larger context I will address in a separate response.

**Comment by radarsat1** [comment]
> Well, this is a different tangent than I was on, but interesting nonetheless. Are you suggesting a replacement for the current family of tcl UIs in the projects directories? Or something more global/generic?

I thought that's what you were suggesting.  You mentioned Qt in your initial post.  Sorry for the misunderstanding in that case.

> My original plan was to get the stk project building in a more recent VS

Does it not?

> with asio

Hopefully it's okay ;)

> then add an OSC interface, with the addressing looking suspiciously similar to the skini format.

This is a good idea, just please make any OSC dependencies selectable at run time.  STK should build with or without an OSC library for example.

**Comment by cepthomas** [comment]
> > Well, this is a different tangent than I was on, but interesting nonetheless. Are you suggesting a replacement for the current family of tcl UIs in the projects directories? Or something more global/generic?
> 
> I thought that's what you were suggesting. You mentioned Qt in your initial post. Sorry for the misunderstanding in that case.

There's a common misconception that Qt is used for building only cross-platform desktop apps. In fact, I have used it for many things, never once with a UI. Basically you can think of the Qt libs/QtCreator IDE/mingw/Qmake combination as an Eclipse CDT on steroids.

> 
> > My original plan was to get the stk project building in a more recent VS
> 
> Does it not?

Nope. If you open old dsw/dsp files in a recent VS, they are automatically updated to the xml sln/vcxproj format. The updated files need a few minor manual fixups so it will build properly. That's what I did with the demo project, and probably should be done with the others in stk/projects. I think the best thing to do is to submit my updated demo project build files and add some verbage to README-Win.txt that describes the process.

> 
> > with asio
> 
> Hopefully it's okay ;)

Seems to be ok, not sure what I was doing wrong before. Oh well.

> 
> > then add an OSC interface, with the addressing looking suspiciously similar to the skini format.
> 
> This is a good idea, just please make any OSC dependencies selectable at run time. STK should build with or without an OSC library for example.

OK. I'll play around with this a bit and then propose a new feature.

**Comment by radarsat1** [comment]
> The updated files need a few minor manual fixups so it will build properly

Ah, okay these manual fix-ups are definitely good to know about, please do document them or make a PR.  I can VS here so I can verify on my side.  I am fine with leaving the project files to automatically update but if they require manual fix-ups it should definitely be fixed.

For OSC, feel free to find your preferred solution but I am most familiar with liblo, which has a C++ interface now, so you might check it out.  Only, it requires C++11, which STK is not a C++ 11 project, but if it's a configure-time optional feature then that's okay.

**Comment by cepthomas** [comment]
PR created.
