### ISSUE TITLE
The samplerate should be a member property of Stk base class

### ISSUE THREAD

**Issue by christophhart** [thestk/stk#91]
It seems that the sample rate is a global static variable in the `Stk` class, which makes it impossible to use the framework in a multi-samplerate environment (eg. with oversampling).

Is there a reason why it can't be made a member variable of the `Stk` base class and adding a virtual function

```cpp

// Two new members:
double objectSampleRate = -1.0;
bool usingObjectSampleRate = false;

/** Can be used to set a samplerate for this object.
 If you call this method, this class instance will use this value 
instead of the global sample rate value. */
virtual void setObjectSampleRate(double sampleRate)
{
    objectSampleRate = sampleRate;
    usingObjectSampleRate = true;
}

/** Returns the sample rate that was set with a call to setObjectSampleRate()
 or the global samplerate as fallback. */
double getObjectSampleRate() const noexcept
{
    if(usingObjectSampleRate)
        return objectSampleRate;
    else
        return getSampleRate() // return the global static as fallback
}
}
```

Also, this way functions which need to update their state when the samplerate changes can simply override the function:

```cpp
class DerivedStk: public Stk
{
    void updateState()
    {
         // setup the processing
    }

    void setObjectSampleRate(double sampleRate) override
    {   
        Stk::setObjectSampleRate(sampleRate);
        updateState();
    }
};
```

DISCLAIMER: the naming is poor (ideally it should be just called `setSampleRate() / getSampleRate()`, but it allows 100% backwards compatibility to legacy code.

EDIT: Also, the handling should be more flexible - the API states that you can't change the samplerate after object instantiation, which might happen for several reasons (the end user changing audio device settings might be the most prominent example).

**Comment by garyscavone** [comment]
STK has been in development for over 20 years now and sometimes it is hard to remember why things were done one way or another. Your suggestion seems logical and I’ll definitely consider it. But I wanted to point out that what truly defines the sample rate of an object is how often its “tick” function is called. Of course, the sample rate is often a critical variable in parameter settings but that said, it is currently possible to implement a multi-sample rate environment in STK by properly controlling the “tick rates” and perhaps “fudging” some variable settings.

**Comment by christophhart** [comment]
> it is currently possible to implement a multi-sample rate environment in STK by properly controlling the “tick rates” 

Not sure if I understand the point, but it sounds to me that this would not truly support multirate processing, but just make it compatible so that it doesn't sound wrong.

If you take for example 4x oversampling of a filter module that needs to be enabled / disabled during processing (eg. via a button on the UI).

The code would look like that:

```cpp
// the input is either oversampled and 4 times as long or the original data with the default samplerate
void oversampled_process(float* data, int numSamples)
{
    int numSamplesPerTick = oversampling_enabled ? 4 : 1; // 4x oversampling, the tick() method will be called every 4 samples

    while(numSamples >= 0)
    {
          float inputValue = *data;

          // zero-pad the input
          memset(data, 0, sizeof(float) * numSamplesPerTick);

          // process the STK module at the original sample rate
          *data = stk_object.tick(inputValue);

          // advance pointer
          data += numSamplesPerTick;
          numSamples -= numSamplesPerTick;
    }
}
```

This renders the entire oversampling process useless, since it will basically run at the original samplerate.

However there might be a workaround on the client side without changing the STK codebase:


```cpp
template <class T> class StkObjectSampleRateWrapper
{
    void setObjectSampleRate(double sampleRate)
    {
        auto global_sample_rate = Stk::sampleRate();
        Stk::setSampleRate(sampleRate);
        object.reset(new StkDerived());
        object->ignoreSampleRateChange();
        stk::setSampleRate(global_sample_rate );
    }

    T* getStkObject() { return object.get(); };

public:
    std::unique_ptr<T> object = nullptr;
};
```

It opposes these restrictions:

- the prepare method must not be used in a multithread environment (so any calls to this method are guaranteed to be subsequentially)
- there might be some unnecessary overhead because it has to create a new object in every prepare call.
- the pointer indirection and memory allocation on the heap might have an impact on cache line performance.

It looks a bit hacky, but I might work around these limitations in my use case.

**Comment by garyscavone** [comment]
Again, the point of my response is that the user is in complete control of the sample rate. There is absolutely no mechanism inherent in the STK code that implements the “ticking” scheme, thus multirate processing should not be a problem. The only issue you may run into is the calculation of filter coefficients when those coefficients are set using methods that refer to the sample rate (for example, the BiQuad::setResonance()). But generally, there are functions that allow you to specify your own filter coefficients (BiQuad::setCoefficients()).

**Comment by garyscavone** [comment]
This is almost two years old and seems stale so I'm closing it.
