### ISSUE TITLE
how to install? 

### ISSUE THREAD

**Issue by mesutsaygioglu** [thestk/stk#92]
i have visual studio 2019 . i tried to place the template file into visual studio user  templastes section but i didn't find it when i tried to create a new project with using stk tamplate. 
My second attempt was installing it by using cmd but since "./configure" doesn't work on windows  i couldn't install it . Is there a step by step instalition guide for begginers like me ?

**Comment by garyscavone** [comment]
There is no “installation” for Windows. If you want, you can try to figure out how to compile a library and use that but you can also just pick and choose the C++ classes you want to use in your projects.

**Comment by mesutsaygioglu** [comment]
Thank you so much! 🙏
