### ISSUE TITLE
[SUGGESTION] Audio fingerprinting

### ISSUE THREAD

**Issue by forart** [thestk/stk#98]
Hi there, I honestly don't know if it's in project goals, but I recently discovered a very cool lib called [Aurio](https://github.com/protyposis/Aurio) that "focuses on audio processing, analysis, media synchronization and media retrieval and implements various audio fingerprinting methods".

As [this video](https://www.youtube.com/watch?v=QXQVPXjR3Lc) demonstrates, those algorithms can align (through its GUI called [AudioAlign](https://github.com/protyposis/AudioAlign)) fingerprinted audios between many tracks.

The drawback is that it has been developed in C# for .NET (it's Windows-only), so it would be really great to establish some kind of collaboration between projects in order to (finally) obtain a platform-indipendent open source multitrack synchronizer.

Last, but not least, I'm pretty sure this kind of coding can be very educational.

Hope that inspires.

**Comment by garyscavone** [comment]
Interesting but not so relevant here.
